import Link from 'next/link';

const services=[['⌂','ساختمان‌سازی','اجرای پروژه‌های مسکونی، تجاری و اداری از ایده تا تحویل.'],['◇','طراحی و معماری','تبدیل ایده‌های معماری به نقشه‌ها و فضاهای دقیق و ماندگار.'],['◈','مدیریت پروژه','کنترل زمان، هزینه و کیفیت با فرآیندهای شفاف مهندسی.']];
const projects=[['برج آفتاب','پروژه مسکونی · تهران','https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=900&q=85'],['خانه باغ سپیدار','ویلای مدرن · کرج','https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=900&q=85'],['مجتمع تجاری آرکا','تجاری · تهران','https://images.unsplash.com/photo-1487958449943-2429e8be8625?auto=format&fit=crop&w=900&q=85']];
export default function Home(){return <>
<section className="hero"><div className="container hero-content"><span className="eyebrow">مهندسی · معماری · اجرا</span><h1>ساختن آینده،<br/>با مهندسی امروز</h1><p>ما پروژه‌های ساختمانی را از نخستین طرح تا آخرین جزئیات، با استانداردهای مهندسی و نگاه دقیق به کیفیت اجرا می‌کنیم.</p><div className="actions"><Link className="btn" href="/projects">مشاهده پروژه‌ها</Link><Link className="btn secondary" href="/contact">درخواست مشاوره</Link></div></div></section>
<section className="section"><div className="container"><div className="section-head"><h2>راهکارهای ما</h2><p>یک تیم یکپارچه برای طراحی، اجرا و مدیریت پروژه‌های ساختمانی شما.</p></div><div className="grid-3">{services.map(([icon,title,text])=><div className="card" key={title}><div className="service-icon">{icon}</div><h3>{title}</h3><p>{text}</p></div>)}</div></div></section>
<section className="section stats"><div className="container stats-grid"><div className="stat"><strong>۱۵+</strong><span>سال تجربه</span></div><div className="stat"><strong>۸۰+</strong><span>پروژه تکمیل‌شده</span></div><div className="stat"><strong>۲۴</strong><span>پروژه فعال</span></div><div className="stat"><strong>۶۰+</strong><span>متخصص و مهندس</span></div></div></section>
<section className="section"><div className="container"><div className="section-head"><h2>پروژه‌های شاخص</h2><Link className="btn" href="/projects">همه پروژه‌ها</Link></div><div className="grid-3">{projects.map(([title,meta,img],i)=><Link className="project" key={title} href={`/projects/${['aftab','sepidar','arka'][i]}`} style={{backgroundImage:`url(${img})`}}><div className="project-info"><h3>{title}</h3><p>{meta}</p></div></Link>)}</div></div></section>
<section className="section"><div className="container split"><div className="image-panel"/><div><span className="eyebrow">چرا آرمان سازه؟</span><h2>جزئیات، تفاوت را می‌سازند.</h2><p>از انتخاب مصالح تا کنترل کیفیت اجرا، تمام مراحل پروژه زیر نظر تیمی متخصص و متعهد پیش می‌رود.</p><div className="feature-list"><div className="feature"><strong>شفافیت در اجرا</strong><br/>گزارش‌دهی و برنامه‌ریزی روشن در تمام مراحل.</div><div className="feature"><strong>کیفیت ماندگار</strong><br/>استانداردهای مهندسی در طراحی و اجرای جزئیات.</div><div className="feature"><strong>تحویل متعهدانه</strong><br/>مدیریت دقیق زمان و هزینه تا روز تحویل.</div></div></div></div></section>
<section className="cta"><div className="container"><h2>پروژه بعدی شما، از یک گفت‌وگو شروع می‌شود.</h2><p>برای بررسی پروژه و دریافت مشاوره با ما در ارتباط باشید.</p><Link className="btn" href="/contact">شروع یک همکاری</Link></div></section>
</>}
